members/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="member_list"),
    path('<int:pk>/', views.DetailView.as_view(), name="member_detail"),
    path('<int:pk>/delete', views.DeleteView.as_view(), name="member_delete"),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import login as login_view
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', login_view, name="login"),

    path('', include('social_django.urls', namespace="social")),
    path('logout/', auth_views.LogoutView.as_view(template_name='members/logout.html'), name='logout'),

    path('members/', include('members.urls')),
    path('meetings/', include('meetings.urls')),

    path('cms/', include('cms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meetings/models.py
from django.db import models
from django.contrib.auth.models import User
import random


class Meeting(models.Model):
    date = models.DateField()
    time = models.TimeField()
    agenda = models.TextField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    members = models.ManyToManyField(User)
    is_active = models.BooleanField(default=False)
    code = models.CharField(max_length=6, blank=True, null=True)

    def __str__(self):
        return f'Spotkanie {str(self.date)} o godzinie {str(self.time)}'

    def save(self, *args, **kwargs):
        if self.is_active and not self.code:
            self.code = f"{random.randint(1, 999999):06d}"
            while Meeting.objects.filter(code=self.code):
                self.code = f"{random.randint(1, 999999):06d}"
        elif not self.is_active and self.code:
            self.code = None
        super().save(*args, **kwargs)

members/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar_url = models.CharField(max_length=255)

    def __str__(self):
        return self.user.email


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

members/forms.py
from django import forms

members/views.py
from django.shortcuts import render, redirect

from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required


from django.views.generic import (
    edit,
    DetailView,
    ListView)

from .models import Profile


def login(request):
    if request.user.is_anonymous:
        return render(request, 'members/login.html')
    else:
        return redirect('meeting_list')


@method_decorator(login_required, name="dispatch")
class IndexView(ListView):
    template_name = 'members/member_list.html'
    model = User
    context_object_name = 'member_list'


@method_decorator(login_required, name="dispatch")
class DetailView(DetailView):
    template_name = 'members/member_detail.html'
    model = User
    context_object_name = 'member'


@method_decorator(staff_member_required, name="dispatch")
class DeleteView(edit.DeleteView):
    template_name = 'members/member_delete.html'
    model = User
    context_object_name = 'member'
    success_url = reverse_lazy('member_list')

members/templates/members/login.html
{% extends 'unauthenticated.html' %}
{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} mx-auto">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="card mx-auto">
            <div class="card-header">
                <h5>Logowanie AKAI</h5>
            </div>
            <div class="card-body text-center">
                <p>Do aplikacji można zalogować się wyłącznie za pomocą maila z domeny @akai.org.pl. Jeżeli nie masz takiego konta napisz do przewodniczącego.</p>
                <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">
                    Login
                </a>
            </div>
        </div>
    </div>
{% endblock %}

members/templates/members/logout.html
{% extends 'unauthenticated.html' %}
{% block content %}
    <div class="card w-50">
        <div class="card-header text-center">
            <h3>Wylogwoano pomyślnie!</h3>
        </div>
        <div class="card-body text-center">
            <a class="btn btn-primary" href="{% url 'login' %}">
                Przejdź do logowania
            </a>
        </div>
    </div>
{% endblock %}

members/templates/members/meeting_member_list.html
{% extends 'akai_manager_python/base.html' %}

members/templates/members/member_delete.html
{% extends 'authenticated.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2 class="text-center my-4">Usuwanie użytkownika "{{member.username}}"</h2>
    <div class="member-edit-container">
        <form method="post">{% csrf_token %}
            <p class="text-center">Czy na pewno chcesz usunąć wybranego użytkownika?</p>
            <input type="submit" value="Usuń" class="btn btn-danger float-right">
            <a class="btn btn-light float-right mr-2" href="{%url 'member_list'%}">Powrót</a>

        </form>
    </div>
{% endblock %}

members/templates/members/member_detail.html
{% extends 'authenticated.html' %}
{% block content %}
    <h2 class="text-center my-4">Dane użytkownika "{{member.username}}"</h2>
    <hr />
    <div class="member-detail-container">
        <div class="row">
            {% if member.profile.avatar_url %}
                <div class="col-12 col-sm-3 col-md-2 col-lg-2 mr-lg-0 member-detail-avatar text-center">
                    <a href="{{ member.profile.avatar_url|default:"https://akai.org.pl/img/logo.svg" }}">
                        <img  src="{{ member.profile.avatar_url| default:"https://akai.org.pl/img/logo.svg" }}" alt="Avatar {{member.username}}" class="bg-dark p-2"/>
                    </a>
                </div>
            {% endif %}
            <div class="col-sm-8 col-md-9 col-lg-10 col-12 mt-1">
                <h5 class="mb-0">Imie i nazwisko:</h5>
                <h3>{{member.first_name|default:'==='}} {{member.last_name|default:'==='}}</h3>
                <p>Adres e-mail: <br> {{member.email}}</p>
            </div>
        </div>
        <a class="btn btn-light float-right bottom-right" href="{%url 'member_list'%}">Powrót do listy członków</a><br>
        <hr class="mt-4">
        <h3 class="text-center my-4">Uczęszczane spotkania</h3>
        {% if member.meeting_set.all %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Data</th>
                    <th>Czas</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for meeting in member.meeting_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ meeting.date }}</td>
                        <td>{{ meeting.time }}</td>
                        <td>{% if meeting.is_active%}
                            <div class="btn btn-success btn-sm">Aktywne</div>
                        {% endif %}
                        </td>
                        <td><a href="{% url 'meeting_view' meeting.id%}">Więcej</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p class="text-center">Brak uczęszczanych spotkań</p>
        {% endif %}
    </div>
{% endblock %}

members/templates/members/member_edit.html
{% extends 'authenticated.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2 class="text-center my-4">Edycja użytkownika {{member.username}}</h2>
    <div class="member-edit-container">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-outline-info float-right" type="submit">
                    Zapisz
                </button>
                <a class="btn btn-light float-right mr-2" href="{% url 'member_list' %}">Powrót</a>
            </div>
        </form>
    </div>
{% endblock %}

members/templates/members/member_list.html
{% extends 'authenticated.html' %}
{% block title %}Lista członków | {% endblock %}
{% block content %}
    <h2 class="text-center my-4">Lista członków</h2>
    <div class="member-list-container">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Imię i nazwisko</th>
                    <th>Nazwa użytkownika</th>
                    <th>Email</th>
                    <th></th>
                    {% if user.is_superuser %}
                    <th></th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for member in member_list %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>
                            {% if member.first_name and member.last_name %}
                                {{member.first_name}} {{member.last_name}}
                            {% else %}
                                =======
                            {% endif %}
                        </td>
                        <td>{{member.username}}</td>
                        <td>{{member.email}}</td>
                        <td><a href="{% url 'member_detail' member.id %}">Szczegóły</a></td>
                        {% if user.is_superuser %}
                            <td><a href="{% url 'member_delete' member.id %}" class="btn btn-danger btn-sm">Delete</a></td>
                        {% endif %}

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

members/templates/members/member_meeting_list.html
{% extends 'authenticated.html' %}